# -*- coding: utf-8 -*-
"""Tidy data files, extracting information from single files, and generate variables for clustering."""


import os
import re
import numpy as np
import pandas as pd
import basics
import global_vars
import log


ENCODING = global_vars.get_value('ENCODING')
ROOT = global_vars.get_value('ROOT')


# %%
class DataTidier(object):
    """用于数据文件的整理."""

    def __init__(self, root=None):
        self.root = ROOT if not root else root
        self.point_dict = {}
        return

    def tidy_all(self, types=('SC', 'GC', 'SGC')):
        """
        Adapter method for tidying all data files.

        This means to fill missing demographic information (e.g., team, country), 
        calculate primary derived race statistics (e.g., normalized ranking, 
        normalized time lag relative to the winner), and add some additional fields (e.g., full name, race/stage info)
        for every cyclists in the list.

        # Warning: This method operates IN-PLACE, which means the tidied file will cover the original copied,
        none-tidied file in the same directory.

        :param types: By default, only the data files of Stage Classification, General Classification
            or Stage General Classification will be tidied.
        :return: The root FULL path storing the tided data files.
        """
        source_dir = os.path.join(self.root, 'Converted_Raw')
        tidy_dir = os.path.join(self.root, 'Converted_Tidied')

        # 对所有文件执行tidy
        file_list = basics.get_file_list(source_dir, extension='.csv')
        path_tidy_log = os.path.join(source_dir, 'tidy_log.txt')
        tidy_log = log.auto_read_log(path_tidy_log)
        cyclists_list = pd.read_csv(ROOT + r'\MetaData\cyclists_list.csv', encoding=ENCODING)

        try:
            for file in file_list:
                file_name = os.path.split(file)[1]
                result_type = re.split('_', file_name)[3]
                if result_type in types and \
                        (file_name not in tidy_log.keys() or tidy_log[file_name] == 'N'):
                    copy_file_path = self.file_copy(file)
                    self.csv_tidy(copy_file_path, cyclists_list)  # Only operates on a copy of the raw file
                    tidy_log[file_name] = 'Y'
        finally:
            log.auto_write_log(tidy_log, path_tidy_log)

        # 将已经写入dict的积分信息写入对应的文件（待完善）
        # for race in self.point_dict.keys():
        #     for year in self.point_dict[race].keys():
        #         for stage in self.point_dict[race][year].keys():
        #             self.write_point_dict(race, year, stage)
        return tidy_dir

    def csv_tidy(self, source_path, cyclists_list, drop_list=('Phase', 'Heat')):
        """
        The core tidying method.

        This method tidies a single .csv file and is called iteratively by self.tidy_all() method.

        :param source_path: The COMPLETE path of the file to be tidied
        :param cyclists_list: The reference list of all cyclists generated by cyclists_list.py module
        :param drop_list: The titles of columns to be removed from the dataframe
        """
        # Vuelta a España的ñ在路径中时用pd.read_csv()无法直接读取（编码问题），会导致无法读取文档，但是内建的open函数可以
        with open(source_path, 'r', encoding=ENCODING) as fr:
            raw_data = pd.read_csv(fr)
            fr.close()
        print("Tidying {} ...".format(os.path.split(source_path)[1]))
        new_data_dict = {}

        # 1.
        # To remove columns specified by parameter "drop_list"
        header_list = list(raw_data.columns)
        drop_list_list = list(drop_list)
        for item in drop_list:
            if item not in header_list:  # If this column has been removed, no need to remove it again
                drop_list_list.remove(item)
        raw_data.drop(drop_list_list, axis='columns', inplace=True)

        # 2.
        # To combine the first name and last name
        if 'Full Name' not in header_list:
            last_names = list(raw_data['Last Name'])
            first_names = list(raw_data['First Name'])
            full_names = [' '.join([first_name, last_name]) for (first_name, last_name) in zip(first_names, last_names)]
            new_data_dict['Full Name'] = full_names
        else:
            full_names = raw_data['Full Name']

        # 3.
        # To get the actual number of participating cyclists (number of starters of the current competition,
        # including DNS, DNF and DSQ cyclists), and to add date information to records of non-finishers.
        n_starters = len(raw_data['Age'])

        # 4.
        # 检查是否每一行都填写了排名和队伍数据，按行遍历
        # 注意pandas读取时已经自动识别表头行，行号计数从数据行开始
        stage_type = os.path.splitext(os.path.split(source_path)[1])[0].split('_')[4]
        for rank in range(n_starters):
            if rank > 0 and pd.isna(raw_data['Rank'][rank]):  # 说明这个选手可能是和上一名选手同名次；注意NaN的布尔值是True
                if raw_data['IRM'][rank] not in ['DNF', 'DNS', 'DSQ']:  # 还需要判断是否为正常完赛
                    if stage_type != 'TTT':
                        raw_data.loc.__setitem__((rank, 'Rank'), raw_data['Rank'][rank - 1])
                        if pd.isna(raw_data['Team'][rank]):
                            raw_data.loc.__setitem__((rank, 'Team'), raw_data['Team'][rank - 1])
                    else:  # 对于TTT赛段，若完赛的车手出现排名数据缺失，则标记为0（表明信息缺失），不检查队伍情况
                        raw_data.loc.__setitem__((rank, 'Rank'), 0)
                """UCI上TTT的数据质量非常差，如果需要的话，考虑从赛事官网直接获取数据"""

        # 5.
        # 计算相对排名
        # 关于DSQ车手：虽然这部分人最终成绩被取消，但是他们的成绩会被用作排名
        # 比如一个DSQ的人排第100位然后成绩被取消，那么第100位的人就会空缺，不会向前候补
        # 为避免出现相对排名>1的情况，目前的排名计算是把DSQ的人也算在基数里
        if not pd.isna(raw_data['Rank'][0]):
            n_finishers = int(max(raw_data['Rank']))
            rank_norm_finishers = raw_data['Rank'] / n_finishers  # nan除以实数结果还是nan，不会报错
        else:
            rank_norm_finishers = raw_data['Rank']
        new_data_dict['Rank_Norm'] = rank_norm_finishers

        # 6.
        # 计算相对完成时差
        time_winner = raw_data['Result'][0]
        time_winner_sec = basics.time2sec(time_winner)
        if not time_winner_sec:  # 如果无人完赛，则time2sec返回none；只要有人完赛，返回值布尔值即为True
            lags_norm = raw_data['Result']
        else:
            lags = raw_data['Result'][1:]
            lags_sec = [0]
            for lag in lags:
                if not pd.isna(lag) and '+' in str(lag):  # 结果中有“+”号，直接判定是完成时差
                    lag_sec = basics.time2sec(lag)
                elif not pd.isna(lag):  # 结果中无”+“号，需要分情况讨论，如果大于冠军时间则说明是完整时长
                    lag_sec = basics.time2sec(str(lag))
                    lag_sec = (lag_sec - time_winner_sec) if lag_sec >= time_winner_sec else lag_sec
                else:
                    lag_sec = lag  # 对应DNF或者DNS，成绩为nan，直接复制。注意：DSQ的车手是有时间成绩的，只是没有排名成绩
                lags_sec.append(lag_sec)
            lags_norm = [lag / time_winner_sec * 100 for lag in lags_sec]
        new_data_dict['Time Lag_Norm'] = lags_norm

        # 7.
        # 提取比赛信息，加入到数据当中
        # dict存储的是提取的全部信息，按照self.game_info返回的次序编号；list存储的是想要添加到文件中的信息
        info_headers_dict = {'Race ID': 0, 'Date': 1, 'Race': 2, 'Stage': 3, 'Result Type': 4, 'Stage Type': 5}
        target_info_headers_list = ['Race ID', 'Date', 'Result Type', 'Stage Type']
        for header in target_info_headers_list:
            if header not in header_list:  # 一旦发现缺一项，就全部重新添加
                info = self.game_info(source_path)
                info_lists = [[info[info_headers_dict[field]]]*n_starters for field in target_info_headers_list]
                new_data_dict.update([(info_header, info_list)
                                      for info_header, info_list in zip(target_info_headers_list, info_lists)])
                break

        # 8.
        # 加入车手ID
        ids_list = []
        order = 0
        for name in full_names:
            cyclist_id = np.nan
            try:
                for cyclist in cyclists_list.iterrows():
                    if cyclist[1]['Full Name'] == name and cyclist[1]['Country'] == raw_data['Country'][order]:
                        cyclist_id = cyclist[1]['ID']
                        break
            # 这一步是为了应对raw_data的Country列比Full Name列短（有的车手缺失信息）的情况
            # 或者是cyclists list文件还没有生成，传入的是空dataframe
            except IndexError or KeyError:
                pass
            finally:
                ids_list.append(cyclist_id)
                order += 1
        new_data_dict.update({'Cyclist ID': ids_list})

        # 把所有数据合并成dataframe并全部重写入文件, 要求每一列的长度相同
        new_data = pd.DataFrame(dict(dict(raw_data), **new_data_dict))
        basics.write_csv_bom(new_data, source_path)

        return

    def game_info(self, file):
        """
        To extract game information from file name or file path.

        :param file: May be the COMPLETE PATH or NAME of the file.
        :return: List of information embedded in and created from the file name.
        """
        info = re.split('[_.]', os.path.split(file)[1])
        date, race, stage, result_type, stage_type = info[0:5]
        race_id = self._create_race_id(date, race, stage)
        return [race_id, date, race, stage, result_type, stage_type]

    @staticmethod
    def file_copy(source_path, source_dir=None, copy_dir=None):
        """
        To copy a single .csv data file.

        The files will be copied to a "counterpart" file directory, which means that the path strings of the copied
        and original file differ only in one directory level, while the other parts (including the file name) remain
        identical.

        :param source_path: The FULL path of the file to be copied.
        :param source_dir: Denotes the directory name at the level at which the copy path differs from the source path.
            By default "Converted_Raw".
        :param copy_dir: Similar to source_dir.
            By default "Converted_Tidied".
        :return: The FULL path of new file copy.
        """
        if not source_dir:
            source_dir = 'Converted_Raw'
        if not copy_dir:
            copy_dir = 'Converted_Tidied'

        pattern_path_str = '(.*?)' + source_dir + '(.*)'
        pattern_path = re.compile(pattern_path_str, re.S)
        copy_path = copy_dir.join([part for part in pattern_path.findall(source_path)[0]])

        if not os.path.exists(os.path.split(copy_path)[0]):
            os.makedirs(os.path.split(copy_path)[0])
        with open(source_path, 'rb') as fr:
            with open(copy_path, 'wb') as fw:
                fw.write(fr.read())
                fw.close()
            fr.close()
        return copy_path

    # # 积分写入功能暂时未启用，代码不完善
    # def add_point_dict(self, race, year, stage, point_scale):
    #     """
    #     将特定年份、特定比赛的UCI积分规则写入；只支持传入单一赛事、单一年份、单一赛段;
    #     只实现计时排名积分奖励的写入，爬坡积分、冲刺积分榜的积分奖励暂定手动写入
    #
    #     :param point_scale: list, 若需要添加多赛事/多年份需要额外写循环
    #     :param race, year, stage: 包含赛事、年份以及赛段序号
    #     """
    #
    #     # 先判断是否已在字典中，若已在则跳过添加
    #     if race not in self.point_dict.keys() or year not in self.point_dict[race].keys() \
    #             or stage not in self.point_dict[race][year].keys():
    #         self.point_dict[race] = {year: {stage: point_scale}}
    #     return
    #
    # def write_point_dict(self, race, year, stage):
    #     # 规定stage用缩写S+数字（赛段）或FC（Final Classification，总成绩）表示
    #     try:
    #         current_point_scale = self.point_dict[race][year][stage]
    #         current_dir = os.path.join(self.root, race, year)
    #         if stage == 'FC':
    #             stage_abbr = 'FC_GC'
    #         else:
    #             stage_abbr = stage + '_SC'
    #         for root, dirs, files in os.walk(current_dir):
    #             for file in files:
    #                 if stage_abbr in file:
    #                     fr = pd.read_csv(file)
    #                     new_data = pd.DataFrame({'BIB': fr['BIB'], 'Points': current_point_scale})  # DataFrame按列插入
    #                     new_file = fr.merge(new_data, how='outer')
    #                     basics.write_csv_bom(new_file, file)
    #     except KeyError:
    #         print('The point scale information has not been added.')
    #     return

    @staticmethod
    def _create_race_id(date, race_abbr, stage, align=2):
        """Create race ID from information extracted from file name."""
        if 'S' in stage:
            stage_number = stage.split('S')[1]
            stage = 'S' + '0' * (align - len(stage_number)) + stage_number
        elif stage == 'FC':
            stage = 'R01'
        elif stage == 'P':
            stage = 'P01'
        else:
            raise ValueError("Invalid stage.")
        return ''.join([race_abbr, date[0:4], stage])


# %%
class DataExtracter(object):
    """用于从原始数据提取出特定的变量，集中到统一的文件中用于聚类."""

    def __init__(self, root=None):
        self.root = ROOT if not root else root
        self.save_root = os.path.join(root, 'Converted_Extracted')
        if not os.path.exists(self.save_root):
            os.makedirs(self.save_root)
        return

    def extract_all(self, race_range='Grand Tour', year_range=None, result_types=('SC', 'SGC', 'GC')):
        """The adapter method for batch extracting information from data files.

        By default, only the Grand Tours and Stage Classification, Stage General Classification
        and General Classification will be extracted.
        """
        tidy_root = os.path.join(self.root, 'Converted_Tidied')
        path_tidy_log = os.path.join(tidy_root, 'tidy_log.txt')
        tidy_log = log.auto_read_log(path_tidy_log)
        path_extract_log = os.path.join(self.save_root, 'extract_log.txt')
        extract_log = log.auto_read_log(path_extract_log)

        if race_range == 'Grand Tour':
            race_range = ['Tour de France', "Giro d'Italia", 'Vuelta a España']
        elif type(race_range) == str:
            race_range = [race_range]

        try:
            for race in race_range:
                if not year_range:
                    # extract all years
                    race_dir = os.path.join(tidy_root, race)
                    for item in os.listdir(race_dir):
                        if os.path.isdir(os.path.join(race_dir, item)):
                            extract_log = self.extract(tidy_root, race, item, result_types, tidy_log, extract_log)
                            log.auto_write_log(extract_log, path_extract_log)
                else:
                    # extract only specified years
                    for year in year_range:
                        extract_log = self.extract(tidy_root, race, year, result_types, tidy_log, extract_log)
                        log.auto_write_log(extract_log, path_extract_log)
        finally:
            log.auto_write_log(extract_log, path_extract_log)
        return

    def extract(self, root, race, year, result_types, tidy_log, extract_log):
        """Extract information for a single race and year.
        
        return: Extract log.
        """
        year = str(year)
        save_dir = os.path.join(self.save_root, race)
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        save_file_name = '_'.join([race, year, 'Extracts.csv'])

        if save_file_name not in extract_log.keys() or \
                extract_log[save_file_name] == 'N':
            source_file_dir = os.path.join(root, race, year)
            file_list = basics.get_file_list(source_file_dir, extension='.csv')
            # Create cyclists start list and extract the demographic information, from the FC_GC file
            # Including: Full name, nationality, team, gender, and age
            extract_df = pd.DataFrame()
            for file in file_list:
                if 'FC_GC' in file:
                    print("---------- Creating start list for {} {} ----------".format(race, year))
                    with open(file, 'r', encoding=ENCODING) as fr:
                        source_data = pd.read_csv(fr)
                        fr.close()
                    extract_df = self.create_start_list(source_data)
                    break
            for file in file_list:
                file_name = os.path.split(file)[1]
                stage, result_type, stage_type = os.path.splitext(file_name)[0].split('_')[2:]
                if result_type in result_types and tidy_log[file_name] == 'Y':
                    print("    ------ Extracting information from {} ------".format(file_name))
                    with open(file, 'r', encoding=ENCODING) as fr:
                        source_data = pd.read_csv(fr)
                        fr.close()
                    extract_df = self.add_extract_info(source_data, extract_df,
                                                       stage_info=[stage, result_type, stage_type])
            basics.write_csv_bom(extract_df, os.path.join(save_dir, save_file_name))
            extract_log[save_file_name] = 'Y'

        return extract_log

    @staticmethod
    def create_start_list(source_data, fields=('Full Name', 'Country', 'Team', 'Gender', 'Age')):
        """Create start list and extract the cyclists' demographic information."""
        start_list = pd.DataFrame(source_data[[field for field in fields]])
        return start_list

    @staticmethod
    def add_extract_info(source_data, extract_df, stage_info, extract_fields=('Rank', 'Rank_Norm', 'Time Lag_Norm')):
        """Add information to the extract data file."""
        new_fields = {}
        for field in extract_fields:
            new_fields[field] = '_'.join(stage_info+[field])
        cyclists = extract_df['Full Name']
        for row in source_data.iterrows():
            cyclist = row[1]['Full Name']
            try:
                match_row = cyclists[cyclists == cyclist].index[0]  # To get the index of row of the cyclist
                for field in extract_fields:
                    extract_df.loc.__setitem__((match_row, new_fields[field]), row[1][field])
            except IndexError:  # If no cyclist matches, adds it as a new row (but this is not supposed to happen)
                new_data = pd.DataFrame(dict([(key, row[1].get(key)) for key in extract_fields]), index=[0])
                extract_df = pd.concat([extract_df, new_data], ignore_index=True, sort=False)
        return extract_df


# %%
class VarGenerator(object):
    """从原始变量数据计算衍生变量，直接用于聚类模型."""

    def __init__(self, root=None):
        self.root = ROOT if not root else root
        self.cluster_root = os.path.join(root, 'For_Clustering')
        return

    def gen_vars_all(self, race_range='Grand Tour', year_range='all', var_list=None):
        """ To calculate variables used directly for clustering and write them into data files """
        var_list = self._gen_var_list(var_list)

        if race_range == 'Grand Tour':
            race_range = ['Tour de France', "Giro d'Italia", 'Vuelta a España']
        elif type(race_range) == str:
            race_range = [race_range]

        for race in race_range:
            file_dir = os.path.join(self.cluster_root, race)
            file_list = basics.get_file_list(file_dir, extension='.csv')
            if year_range == 'all':
                for file in file_list:
                    file_year = os.path.split(file)[1].split('_')[1]
                    print("----Generating variables for {} {}...----".format(race, file_year))
                    self.gen_vars(file, var_list)
            else:
                if type(year_range) == str or type(year_range) == int:
                    year_range = [year_range]
                for file in file_list:
                    file_year = os.path.split(file)[1].split('_')[1]
                    if file_year in year_range or int(file_year) in year_range:
                        print("----Generating variables for {} {}...----".format(race, file_year))
                        self.gen_vars(file, var_list)
        return

    def gen_vars(self, source_path, var_list):
        with open(source_path, 'r', encoding=ENCODING) as fr:
            source_data = pd.read_csv(fr)
            fr.close()
        gen_data = source_data
        for var in var_list:
            if var[0] != 'S' and var[0] != 'F':
                continue
            elif 'stage_list' not in dir():
                stage_list = None
            if 'SC_rank_abs' in var or var == 'stages_finished':
                gen_data, stage_list = self._gen_single_var(gen_data, var, stage_list)
            else:
                gen_data = self._gen_single_var(gen_data, var)[0]
        basics.write_csv_bom(gen_data, source_path)
        return

    @staticmethod
    def _gen_single_var(source_data, var, stage_list=None):
        """
        :param source_data:
        :param var:
        :param stage_list: When calculating Stage Classification Ranking (abs)-related variables,
                           stage list can be imported
        :return: The dataframe with variables added and stage list (if applicable)
        """
        cols = source_data.columns
        if not stage_list or len(stage_list) == 0:
            stage_list = []

        if var == 'stages_finished':
            if not stage_list:
                for col in cols:
                    if 'S' in col.split('_')[0] and 'SC' in col and 'Rank' in col and 'Norm' not in col:
                        stage_list.append(col)
            for row in source_data.iterrows():
                count = 0
                for stage in stage_list:
                    if basics.is_number(row[1][stage]):
                        count += 1
                source_data.loc.__setitem__((row[0], var), count)
        elif var == 'GC_rank_abs':
            for row in source_data.iterrows():
                source_data.loc.__setitem__((row[0], var), row[1]['FC_GC_IRR_Rank'])
        elif 'SC_rank_abs' in var:
            if not stage_list:
                for col in cols:
                    if 'S' in col.split('_')[0] and 'SC' in col and 'Rank' in col and 'Norm' not in col:
                        stage_list.append(col)
            for row in source_data.iterrows():
                temp_list = []
                if 'all' in var:
                    for stage in stage_list:
                        if basics.is_number(row[1][stage]):
                            temp_list.append(row[1][stage])
                elif 'IRR' in var:
                    for stage in stage_list:
                        if 'TT' not in stage and basics.is_number(row[1][stage]):
                            temp_list.append(row[1][stage])
                elif 'TT' in var:
                    for stage in stage_list:
                        if 'TT' in stage and basics.is_number(row[1][stage]):
                            temp_list.append(row[1][stage])
                if len(temp_list) > 0:
                    if 'mean' in var:
                        source_data.loc.__setitem__((row[0], var), sum(temp_list)/len(temp_list))
                    elif 'max' in var:
                        source_data.loc.__setitem__((row[0], var), min(temp_list))
                    elif 'SD' in var:
                        source_data.loc.__setitem__((row[0], var), np.std(temp_list))
                else:
                    source_data.loc.__setitem__((row[0], var), np.nan)
        elif 'max_SGC' in var:
            if var == 'GC-max_SGC' and 'stage_max_SGC' in cols:  # 如果最大单站总排名已经算过，就不用再算一遍了
                for row in source_data.iterrows():
                    if basics.is_number(row[1]['stage_max_SGC']):
                        source_data.loc.__setitem__((row[0], var), row[1]['FC_GC_IRR_Rank'] - row[1]['stage_max_SGC'])
            else:
                if not stage_list:
                    for col in cols:
                        if 'SGC' in col and 'Rank' in col and 'Norm' not in col:
                            stage_list.append(col)
                for row in source_data.iterrows():
                    max_list = [999, 0]  # 前面的表示最高SGC，后面的表示对应的赛段；注意高排名对应低数值
                    for stage in stage_list:
                        if basics.is_number(row[1][stage]) and row[1][stage] < max_list[0]:
                            max_list[0] = row[1][stage]
                            max_list[1] = int(stage.split('_')[0].split('S')[1])
                    if var == 'stage_max_SGC':
                        source_data.loc.__setitem__((row[0], var), max_list[0])
                    else:
                        source_data.loc.__setitem__((row[0], var), row[1]['FC_GC_IRR_Rank'] - max_list[0])
        elif 'SC_time_lag_norm' in var:
            if not stage_list:
                for col in cols:
                    if 'S' in col.split('_')[0] and 'SC' in col and 'Time_Lag' in col:
                        stage_list.append(col)
            for row in source_data.iterrows():
                temp_list = []
                if 'all' in var:
                    for stage in stage_list:
                        if basics.is_number(row[1][stage]):
                            temp_list.append(row[1][stage])
                elif 'IRR' in var:
                    for stage in stage_list:
                        if 'TT' not in stage and basics.is_number(row[1][stage]):
                            temp_list.append(row[1][stage])
                if len(temp_list) > 0:
                    if 'mean' in var:
                        source_data.loc.__setitem__((row[0], var), sum(temp_list)/len(temp_list))
                else:
                    source_data.loc.__setitem__((row[0], var), np.nan)
        else:   # If none of the case matches, then leave the data unchanged
            pass
        return source_data, stage_list

    @staticmethod
    def _gen_var_list(option='lite'):
        """
        Generate list for variables to be calculated
        :param option: Can be 'full'(explicit list), 'lite' or None(short list), or a list of name of variables
        """
        if option == 'full':
            var_list = [
                'stages_finished',
                'mean_SC_rank_abs_all', 'mean_SC_rank_abs_TT', 'mean_SC_rank_abs_IRR',
                'mean_SC_rank_norm_all', 'mean_SC_rank_norm_TT', 'mean_SC_rank_norm_IRR',
                'mean_SC_time_lag_norm_all', 'mean_SC_time_lag_norm_TT', 'mean_SC_time_lag_norm_IRR',
            ]
        elif option == 'lite' or not option:
            var_list = [
                'stages_finished', 'GC_rank_abs',                           # 完成的赛段数，最终总排名
                'mean_SC_rank_abs_all', 'mean_SC_rank_abs_IRR',             # 平均单站排名
                'max_SC_rank_abs_all', 'max_SC_rank_abs_IRR',               # 最高单站排名
                'SD_SC_rank_abs_all', 'SD_SC_rank_abs_IRR',                 # 单站排名标准差
                'stage_max_SGC', 'GC-max_SGC',                              # 第一次取得最高总排时的赛段，全程最高总排和最终总排差
                'mean_SC_time_lag_norm_all', 'mean_SC_time_lag_norm_IRR',   # 与赛段冠军的完赛时差百分比均值
            ]
        elif type(option) == list:
            var_list = option
        else:
            var_list = None
        return var_list
